on: push
name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Mod
      uses: Xorimuth/factorio-mod-portal-publish@vversion
      env:
        FACTORIO_PASSWORD: ${{ secrets.FACTORIO_PASSWORD }}
        FACTORIO_USER: ${{ secrets.FACTORIO_USER }}
